/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        text: 'var(--text)',
        muted: 'var(--textMuted)',
        border: 'var(--border)',
        accent: 'var(--accent)',
        accent2: 'var(--accent2)',
        // Studio brand palette (blue / cyan / violet) — used by light AntD pages
        brand: {
          DEFAULT: '#2563eb',
          light: '#3b82f6',
          dark: '#1e40af',
          ink: '#0b1220',
          cyan: '#22d3ee',
          violet: '#a78bfa',
        },
        // ── Synthetica 深色「指挥中心」设计系统(移植自旧 市场调研 工程)──
        background: '#0b1326',
        surface: '#0b1326',
        'surface-dim': '#0b1326',
        'surface-bright': '#31394d',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-variant': '#2d3449',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#c7c4d7',
        'on-background': '#dae2fd',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        outline: '#908fa0',
        'outline-variant': '#464554',
        primary: '#c0c1ff',
        'on-primary': '#1000a9',
        'primary-container': '#8083ff',
        'on-primary-container': '#0d0096',
        'inverse-primary': '#494bd6',
        'primary-fixed': '#e1e0ff',
        secondary: '#4edea3',
        'on-secondary': '#003824',
        'secondary-container': '#00a572',
        'on-secondary-container': '#00311f',
        'secondary-fixed': '#6ffbbe',
        tertiary: '#ffb783',
        'on-tertiary': '#4f2500',
        'tertiary-container': '#d97721',
        'on-tertiary-container': '#452000',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        sans: ['Inter', 'Noto Sans SC', 'system-ui', 'sans-serif'],
        serif: ['Source Serif Pro', 'Georgia', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        'data-lg': ['JetBrains Mono', 'monospace'],
        'data-sm': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-caps': ['11px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' }],
        display: ['26px', { lineHeight: '1.25', letterSpacing: '-0.02em', fontWeight: '700' }],
        'data-lg': ['18px', { lineHeight: '1.2', fontWeight: '500' }],
        'data-sm': ['12px', { lineHeight: '1.0', fontWeight: '400' }],
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '20px',
        'container-margin': '40px',
      },
    },
  },
  plugins: [],
};
