/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        text: 'var(--text)',
        muted: 'var(--textMuted)',
        border: 'var(--border)',
        accent: 'var(--accent)',
        accent2: 'var(--accent2)',
        // Studio brand palette (blue / cyan / violet) — used by light AntD pages
        brand: {
          DEFAULT: '#2563eb',
          light: '#3b82f6',
          dark: '#1e40af',
          ink: '#0b1220',
          cyan: '#22d3ee',
          violet: '#a78bfa',
        },
        // ── Aura Minimalist 浅色设计系统(token 名沿用,值改为浅色)──
        // Chrome/中性:纯白抬升面 + 极浅灰背景,靠柔和阴影分层
        background: '#f8f9fa',
        surface: '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-variant': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#444748',
        'on-background': '#191c1d',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        outline: '#747878',
        'outline-variant': '#c4c7c8',
        // primary = Aura 中性灰(外壳/按钮/图表 chrome)
        primary: '#5d5f5f',
        'on-primary': '#ffffff',
        'primary-container': '#e7e8e9',
        'on-primary-container': '#444748',
        'inverse-primary': '#c6c6c7',
        'primary-fixed': '#e2e2e2',
        // secondary = GO/正向语义绿(浅底可读)+ Aura 蓝灰中性药丸(*-fixed)
        secondary: '#2e7d5b',
        'on-secondary': '#ffffff',
        'secondary-container': '#c9efd9',
        'on-secondary-container': '#0f4c34',
        'secondary-fixed': '#d6e0f3',
        'on-secondary-fixed': '#121c2a',
        'on-secondary-fixed-variant': '#3d4756',
        // tertiary = 警示琥珀
        tertiary: '#b45309',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#ffe2b8',
        'on-tertiary-container': '#5a3200',
        // error = 风险红
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Hanken Grotesk', 'Inter', 'Noto Sans SC', 'system-ui', 'sans-serif'],
        serif: ['Source Serif Pro', 'Georgia', 'serif'],
        'body-md': ['Hanken Grotesk', 'Inter', 'sans-serif'],
        'headline-sm': ['Hanken Grotesk', 'Inter', 'sans-serif'],
        'label-caps': ['Hanken Grotesk', 'Inter', 'sans-serif'],
        display: ['Hanken Grotesk', 'Inter', 'sans-serif'],
        'data-lg': ['Hanken Grotesk', 'Inter', 'sans-serif'],
        'data-sm': ['Hanken Grotesk', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-caps': ['11px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' }],
        display: ['26px', { lineHeight: '1.25', letterSpacing: '-0.02em', fontWeight: '700' }],
        'data-lg': ['18px', { lineHeight: '1.2', fontWeight: '500' }],
        'data-sm': ['12px', { lineHeight: '1.0', fontWeight: '400' }],
      },
      // Aura 药丸/柔和圆角标度(spacing 名同值不同,为避免全站重排保持现值)
      borderRadius: {
        DEFAULT: '0.75rem',
        md: '1rem',
        lg: '1.25rem',
        xl: '1.75rem',
        '2xl': '2.25rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '20px',
        'container-margin': '40px',
      },
    },
  },
  plugins: [],
};
